### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by Drummondh** [jaggr2/node-red-contrib-aggregator#1]
It appears the node is rounding  values to the nearest whole number when aggregating Min and Max values.  Is this the intent?

**Comment by jaggr2** [comment]
No, it isn't. I quickly checked the code and the source of the problem is probably on line 106 in the aggregator.js file ( https://github.com/jaggr2/node-red-contrib-aggregator/blob/master/aggregator/aggregator.js#L106 ). There the msg.payload is wrapped with the parseInt function, which should be parseFloat.

I'll make a bugfix as soon I'll have some free time (hoping today/tomorrow :) )

**Comment by Drummondh** [comment]
Thank you!  That will save me having to do a lot of extra functions to
multiply and divide....

**Comment by Drummondh** [comment]
I made the change locally and it appears to be working correctly.

**Comment by jaggr2** [comment]
I've made a bugfix and successfully tested it with node-red version 0.14.6. The bugfix is released and published as version 1.1.0 on npm.
