### ISSUE TITLE
Node doesn't work with input that has no topic key in data, even though the output of this node doesn't even include the topic

### ISSUE THREAD

**Issue by thomasvnl** [jaggr2/node-red-contrib-aggregator#7]
Passing data to this node that does not contain a topic results in the following error being thrown:

```
msg : string[44]
"Cannot read property 'toString' of undefined"
```

This seems odd behaviour, especially when I consider the fact that the output of this node, even if you include a valid topic on the input, never uses any topic on the output. I tested this with two injectors, both with a different topic so one of them had topic "A", the other had "B", and I injected only the value of 1 on topic A, and only the value of 2 on topic B. What I got surprised me a bit (because this node's README states something else!), because I received 1.5 (the average of course), instead of an average of 1 on topic A, and an average of 2 on topic B. 

Clearly, something is broken.

**Comment by jaggr2** [comment]
Hi, I finally found some time to look at this issue. You're right; this error should not be thrown. I will make a fix for it so that undefined, null or empty topics will be treated as the same value.

> What I got surprised me a bit (because this node's README states something else!), because I received 1.5 (the average of course), instead of an average of 1 on topic A, and an average of 2 on topic B.

The README states following aggregation formula:

> 1. Aggregation of all retrieved values per topic by the defined aggregation method
> 2. Aggregation of the aggregation results of each topic again by the defined aggregation method

Point 2 is the reason why you received just 1.5 and not a value per topic. Issue #6 proposes to make this behavior configurable which in my opinion is probably the best way to keep both backwards compatibility and make the aggregation behavior less confusing.

**Comment by gormac** [comment]
Ping! Do you accept pull requests? It seems like an easy fix/workaround.

**Comment by jaggr2** [comment]
Yes, I do, feel free to submit one and I'll merge it. I'm quite busy these times to do the fix on my own, but I appreciate any help!

**Comment by gormac** [comment]
@jaggr2 just in case you've missed it: #11
