### ISSUE TITLE
Installing aggregator on UBUNTU - ERR

### ISSUE THREAD

**Issue by fritserasmus** [jaggr2/node-red-contrib-aggregator#9]
This is not an issue - This is stupid user!

I am running Node-RED on Ubuntu 16.04 Server.

The dashboard is unresponsive so I found the solution: Use the aggregator.

Installing from root: npm install node-red-contrib-aggregator
Instructions states: In your Node-RED directory, execute:   

     Gives Error message:

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-aggregator"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!

It is most probably I am in wrong directory when I execute the instruction:
On UBUNTU, where is the Node-RED directory?

Thanking in advance

**Comment by jaggr2** [comment]
Hi! 

The EAI_AGAIN Error from the npm tool indicates a DNS issue, which means that the npm tool was not able to resolve the domain registry.npmjs.org into it's corresponding IP address. This could be due to a wrong dns configuration on your server, a wrong configuration on the dns server your ubuntu server is using or a problem with the network itself like temporary connection failure, a firewall who is blocking your dns-packet, etc.

Here is an answer from someone with a temporary workaround: https://github.com/npm/npm/issues/15059#issuecomment-352917606

To your question about where the Node-RED directory is: this depends on how you installed node-red. If you followed the instructions from https://nodered.org/docs/getting-started/installation , then you can execute

`npm root -g`

and it will show you the path of the directory where you should find the node-red directory. See also this answer here: https://stackoverflow.com/questions/5926672/where-does-npm-install-packages

**Comment by fritserasmus** [comment]
@jaggr2 , 
Thanks Roger

I updated my nameservers to 8.8.8.8 and that did the trick.
I managed to install the aggregator and now my dashboard manages to keep up.

Thanks for pinpointing the issue!
